name: find tabs in code

on :
  push:
    branches: 
      - main  

jobs:
  prepare: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get changes files
        id: files
        uses: tj-actions/changed-files@v19
        with:
          files_ignore: |
            *.yml
            *.yaml
  
      - name: list
        run: |
          for file in ${{ steps.files.outputs.all_changed_files }}; do
            echo "$file"
          done

      - name: Scan files
        run: |
          grep $'\t' ${{ steps.files.outputs.all_changed_files }} > ${{ steps.files.outputs.all_changed_files  }}.log 
      
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.files.outputs.all_changed_files }}.log

