name: find tabs in code

on :
  push:
    branches: 
      - main  

jobs:
  prepare: 
    runs-on: ubuntu-latest
    outputs: 
      output1: ${{ steps.files.outputs.files }}
    steps:
      - uses: actions/checkout@v3

      - name: Get changes files
        id: base
        uses: tj-actions/changed-files@v19
        with:
          files_ignore: |
            *.yml
            *.yaml

      - name: Convert file to JSON
        id: files
        run: echo "::set-output name=files::${{ steps.base.outputs.all_changed_files }}"

      - name: list
        run: |
          for file in ${{ steps.files.outputs.all_changed_files }}; do
            echo "$file"
          done
  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        check_files: ${{ fromJson(needs.prepare.outputs.output1) }}
    
    steps:
      - uses: actions/checkout@v3    

      - name: Scan files
        run: |
          grep $'\t' ${{ matrix.check_files }} > ${{ matrix.check_files }}.log 
      
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.check_files }}.log

